# Generated by Django 5.2.7 on 2025-11-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'can create books'), ('can_view', 'can view books'), ('can_edit', 'can edit books'), ('can_delete', 'can delete books')]},
        ),
    ]
